apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-engine
  template:
    metadata:
      labels:
        app: match-engine
    spec:
      containers:
      - name: match-engine
        image: match-engine:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: match-engine-service
spec:
  selector:
    app: match-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
